True ==> increment_time()
True ==> update_workers_needed()
True ==> update_employed_population()
True ==> update_budget()
True ==> simulate_farm_growth()
True ==> simulate_industry_production()
age%year == 0 ==> change_budget_allocation()
True ==> process_user_input(get_user_input())
